### PR TITLE
Add Eclipse import howto

### PR DESCRIPTION
**Pull request by alin-amana**

### CODE REVIEW

**Comment by alin-amana** [comment]
Hmm... Looks like GitHub isn't cooperating.

**Comment by KlimovichYauhen** [comment]
Yes, I approved multiple times already. Still 'Review required...' is on the page

**Comment by alin-amana** [comment]
OK, figured it out. You're not part of the secret *Core* team (woo, scary!), so at first I couldn't even ask you for a review. Then I added *nexus-nlp* as a team in the repository settings, but I neglected to add it with *Write* rights, so now you could review, and approve (interestingly enough) but your approval wasn't worth a damn to GitHub.

I've now added *nexus-nlp* with *Write* access to the repo, so we're fine. I also asked Silvan to add you to the *Core* team. No idea why it's secret (woo!).

**Comment by KlimovichYauhen** [comment]
Great, now thanks to you and @whiletrue I'm in the blessed _Core_ team 👍

**Pull request merged**
